from . import const

# Experiments and their parameters
JPARC_tau_per_POT = 4e-9
NuMI_tau_per_POT = 2.9e-7
SPS_tau_per_POT = 1.7e-6

sigma_tau = 0.22 * const.mbarn_to_cm2  # cm^2
luminosity_LHC = 150e39  # 1/cm^2
luminosity_HL_LHC = 3e42  # 1/cm^2

# xsec_hard = {"120GeV": 0.7, "400GeV": 0.0168063, "13.6TeV": 0}  # mb pT > 3 GeV
xsec_hard = {"120GeV": 0.000677308, "400GeV": 0.0168063, "13.6TeV": 0}  # mb pT > 3 GeV
xsec_soft = {"120GeV": 38.4539, "400GeV": 39.8586, "13.6TeV": 102.253}  # mb pT < 3 GeV
xsec_tot = {key: xsec_hard[key] + xsec_soft[key] for key in xsec_hard.keys()}  # mb

EXPERIMENTS: dict[str, dict] = {
    "ND280": {
        "name": "ND280",
        "L": 280e2,
        "x0": 10.75e2,
        "y0": 0,
        "dX": 1.7e2,
        "dY": 1.96e2,
        "dZ": 3 * 56,
        "active_volume": True,
        "norm": JPARC_tau_per_POT * (12.34e20 + 6.29e20),
        "Emin": 0.05,
        "final_states": ["ee", "em", "me", "mm"],
    },
    "ICARUS": {
        "name": "ICARUS",
        "L": 803e2,
        "x0": 0.0968 * 803e2,
        "y0": 0,
        "dX": 2 * 2.67e2,
        "dY": 2.86e2,
        "dZ": 17.00e2,
        "active_volume": True,
        "norm": NuMI_tau_per_POT * 3e21,
        "Emin": 0.1,
        "final_states": ["ee", "em", "me", "mm", "gg"],
    },
    "MicroBooNE": {
        "name": "MicroBooNE",
        "L": 685e2,
        "x0": 0.146 * 685e2,
        "y0": 0,
        "dX": 2.26e2,
        "dY": 2.03e2,
        "dZ": 9.42e2,
        "active_volume": True,
        "norm": NuMI_tau_per_POT * 2e21,
        "Emin": 0.1,
        "final_states": ["ee", "em", "me", "mm", "gg"],
    },
    "NoVA": {
        "name": "NOvA",
        "L": 990e2,
        "x0": 14.6e-3 * 990e2,
        "y0": 0,
        "dX": 3.9e2,
        "dY": 3.9e2,
        "dZ": 12.7e2,
        "active_volume": True,
        "norm": NuMI_tau_per_POT * 4.2e21,
        "Emin": 0.1,
        "final_states": ["ee", "em", "me", "mm", "gg"],
    },
    "DUNE": {
        "name": "DUNE-ND",
        "L": 574e2,
        "x0": 0,
        "y0": 0,
        "dX": 5e2,
        "dY": 5e2,
        "dZ": 5.88e2,
        "active_volume": True,
        "norm": NuMI_tau_per_POT * 10 * 1.1e21,
        "Emin": 1,
        "final_states": ["ee", "em", "me", "mm", "gg"],
    },
    "TwoByTwo": {
        "name": "2x2 protoDUNE-ND",
        "L": 1035e2,
        "x0": 0,
        "y0": 0,
        "dX": 2 * 0.7e2,
        "dY": 1.4e2,
        "dZ": 2 * 0.7e2,
        "active_volume": True,
        "norm": NuMI_tau_per_POT * 1e21 * 0.87,
        "Emin": 0.1,
        "final_states": ["ee", "em", "me", "mm", "gg"],
    },
    "TwoByTwo_absorber": {
        "name": "2x2 protoDUNE-ND absorber",
        "L": 1035e2 - 715e2,
        "x0": 0,
        "y0": 0,
        "dX": 2 * 0.7e2,
        "dY": 1.4e2,
        "dZ": 2 * 0.7e2,
        "active_volume": True,
        "norm": NuMI_tau_per_POT * 1e21 * 0.13,
        "Emin": 0.1,
        "final_states": ["ee", "em", "me", "mm", "gg"],
    },
    "ArgoNeuT": {
        "name": "ArgoNeuT",
        "L": 1033e2 - 63,
        "x0": 0,
        "y0": 0,
        "dX": 0.40e2,
        "dY": 0.47e2,
        "dZ": 0.90e2 + 63,
        "active_volume": True,
        "norm": NuMI_tau_per_POT * 1.25e20 * 0.5 * 0.87,  # for efficiency,
        "Emin": 10,
        "final_states": ["mm"],
    },
    "ArgoNeuT_absorber": {
        "name": "ArgoNeuT_absorber",
        "L": 1033e2 - 63 - 715e2,
        "x0": 0,
        "y0": 0,
        "dX": 0.40e2,
        "dY": 0.47e2,
        "dZ": 0.90e2 + 63,
        "active_volume": True,
        "norm": NuMI_tau_per_POT * 1.25e20 * 0.5 * 0.13,  # for efficiency,
        "Emin": 10,
        "final_states": ["mm"],
    },
    "CHARM": {
        "name": "CHARM",
        "L": 480e2,
        "x0": 5e2,
        "y0": 0,
        "dX": 3e2,
        "dY": 3e2,
        "dZ": 35e2,
        "norm": SPS_tau_per_POT * 2.4e18,
        "active_volume": False,
        "Emin": 1,
        "final_states": ["ee", "em", "me", "mm", "gg"],
    },
    "BEBC": {
        "name": "BEBC",
        "L": 404e2,
        "x0": 0,
        "y0": 0,
        "dX": 3.57e2,
        "dY": 2.52e2,
        "dZ": 1.85e2,
        "active_volume": True,
        "norm": SPS_tau_per_POT * 2.72e18,
        "Emin": 1,
        "final_states": ["ee", "em", "me", "mm", "gg"],
    },
    # NA62 : {
    #     "name": "NA62",
    #     "L": 79.4e2,
    #     "x0": 0,
    #     "y0": 0,
    #     "dX": 2e2,
    #     "dY": 2e2,
    #     "dZ": 78e2,
    #     "norm": SPS_tau_per_POT * 1.4e17,
    #     "Emin": 1,
    #     "final_states": ["ee", "mm"],
    # }
    "PROTO_DUNE_NP02": {
        "name": "ProtoDUNE-NP02",
        "L": 677e2,
        "x0": 3e2,
        "y0": 1.5e2,
        "dX": 6e2,
        "dY": 7e2,
        "dZ": 6e2,
        "active_volume": True,
        "norm": SPS_tau_per_POT * 1.75e19,
        "Emin": 1,
        "final_states": ["ee", "em", "me", "mm", "gg"],
    },
    "PROTO_DUNE_NP04": {
        "name": "ProtoDUNE-NP04",
        "L": 723e2,
        "x0": 3e2,
        "y0": 1.5e2,
        "dX": 6e2,
        "dY": 7e2,
        "dZ": 6e2,
        "active_volume": True,
        "norm": SPS_tau_per_POT * 1.75e19,
        "Emin": 1,
        "final_states": ["ee", "em", "me", "mm", "gg"],
    },
    "SHiP": {
        "name": "SHiP",
        "L": 33.7e2,
        "x0": 0,
        "y0": 0,
        "dX": 2.5e2,
        "dY": 4.3e2,
        "dZ": 49.6e2,
        "active_volume": False,
        "norm": SPS_tau_per_POT * 6e20,
        "Emin": 1,
        "final_states": ["ee", "em", "me", "mm", "gg"],
    },
    "FASER": {
        "name": "FASER",
        "L": 480e2,
        "x0": 6.5,
        "y0": 0,
        "R": 0.1e2,
        "dZ": 1.5e2,
        "active_volume": False,
        "norm": luminosity_LHC * sigma_tau,
        "Emin": 100,
        "final_states": ["ee", "em", "me", "mm", "gg"],
    },
    "FASER2": {
        "name": "FASER2",
        "L": 480e2,
        "x0": 0,
        "y0": 0,
        "R": 1e2,
        "dZ": 5e2,
        "active_volume": False,
        "norm": luminosity_HL_LHC * sigma_tau,
        "Emin": 100,
        "final_states": ["ee", "em", "me", "mm", "gg"],
    },
}
